### PR TITLE
linux installer + masks + other stuff\

### PR DESCRIPTION
**Pull request by sh9r**
whipped this up in <15 minutes, just let me know if there are any prevalent issues i need to fix

[to-do]
-add support for other distros using the `uname` command
-fix some folder shennagians 
-spelling issues

### CODE REVIEW

**Comment by couleurm** [comment]
> a lot of people put a lot of time an effort into making this, wo please joing our discord (https://discord.gg/ctt)

* is `wo` a typo?
* could you move this to [/installers/](https://github.com/couleur-tweak-tips/Smoothie/tree/master/install)

Where does the Smoothie folder end up in?

**Comment by sh9r** [comment]
smoothie's folder ends up in the home directory

**Comment by sh9r** [comment]
added csgo mask

**Comment by Aetopia** [comment]
Debian Support please.

**Comment by couleurm** [comment]
Could you name is `csgo.png` and make it 1920x1080?

**Comment by vladaad** [comment]
please split the mask into another PR, you're mixing 2 different things

**Comment by vladaad** [comment]
since this install script is for arch/pacman based distros only, I'd recommend making a PKGBUILD and uploading it to the AUR instead

**Comment by couleurm** [comment]
yes that would be strongly prefered

**Comment by sh9r** [comment]
> please split the mask into another PR, you're mixing 2 different things

haven't been online in the past few days, will clean up everything including adding a debian install script and considering other distros like fedora and nix or void

thanks for sticking with me

**Pull request closed without merging**
